on: [push]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - run: apt install -y texlive-latex-extra texlive-pstricks texlive-lang-french
    - uses: actions/checkout@v2
    - name: pdflatex
      run: ./build.sh
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: corrections
        path: corriges
