on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - run: sudo apt install -y texlive-latex-extra texlive-pstricks texlive-lang-french
    - uses: actions/checkout@v2
    - name: pdflatex
      run: chmod +x ./build.sh && ./build.sh
      shell: bash
    - name: create-artifact
      uses: actions/upload-artifact@v2
      with:
        name: corrections
        path: corriges
    - name: create-release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{GITHUB_SHA}}
        artifacts: "corriges/*.pdf"
        name: "corrections"
